language: c
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - cmake
    - cmake-data
    - gcc-5
    - clang
    - check
    - libsubunit-dev
    - libevent-dev
sudo: required
dist: trusty
compiler:
- gcc
- clang
git:
  submodules: false
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
install: if [ "$CC" = "gcc" ]; then export CC="gcc-5"; fi
before_script:
- mkdir build
- cd build
- cmake ..
script: make
notifications:
  slack:
    secure: nhqRAvzHqP7QThGBUSgLmtb4b3PHFHGNwae5BdZM6fpU/pWicmV/wor40kdO6wTVzgDf3v/4ahl1q31cHczTmGxJ5btuIwiKY9w8zdS8T95+Pi7Y403+Zgtux5paVjJFV0xfniJ6G0k1p1sMujfbGhjTxeLWPnUOUas0hnNkounVXtxa2cnZ2AkJwyCrUIOeOVgIYq0nwOS7MFICUC9tXdBeW4JqxJ3yH3oOKokrmoBS83izuHTXQm1Q3bJ11Oa9SBl89QaO4mLO21MeQjAC9I/Ndf9rO2Uw/om2sEgUw8G3clgDXkkJTDWKJ+fGCmVw8mVFW7M7+fOoz8oCqquzPYkf/ZzXCL410zDPJ2ypv0k89Kwnea/voAVT/y7KwsdBuqgWUpKdYBxTluOES5OnzS/TYj5jRNkqa0r8Knw0opwQFOxRZQ39xqbjgT2gc8ujob/IyVM8RXe5sfjlO3fpucfT4/2qIG0uchoeuwZ5AwV7ohTyIESi0o3Quhfb7q197gQaLn22SZkuhVfMFdrS1Mu81E74GLaLer/MTt1O5xulrzWW0Fbf73ogvNgfi5aytABooxARSJDeB/5cYMLxd8ZVW5niR8vNa+Sg7ewj8FUmBi5QmEa6dFGn/U35Py8QjvxVN1JTw3xR4a4LP58rqLgKq1CrKUdW2hjwxB7eVyc=
