FROM debian:9

ADD . /root/project

RUN apt-get update && apt-get -y install \
        gcc \
        cmake \
        make \
        libevent-dev \
        pkg-config

RUN cd /root/project && rm -rf build && mkdir build && cd build && cmake .. && make

